config/routes.rb
Eetarp::Application.routes.draw do
  root :to => 'blue_sparks/pages#show', :slug => 'home'

  match '/solutions' => 'blue_sparks/pages#show', :slug => 'solutions'
  match '/products' => 'blue_sparks/pages#show', :slug => 'products'
  match '/services' => 'blue_sparks/pages#show', :slug => 'services'
  match '/company' => 'blue_sparks/pages#show', :slug => 'company'

  match '/solutions/electrical_safety' => 'blue_sparks/pages#show', :slug => '/solutions/electrical_safety'
  match '/solutions/power_quality' => 'blue_sparks/pages#show', :slug => '/solutions/power_quality'
  match '/solutions/energy_management' => 'blue_sparks/pages#show', :slug => '/solutions/energy_management'

  match '/products/algodue' => 'blue_sparks/pages#show', :slug => '/products/algodue'
  match '/products/atlantic_scientific' => 'blue_sparks/pages#show', :slug => '/products/atlantic_scientific'
  match '/products/bender' => 'blue_sparks/pages#show', :slug => '/products/bender'
  match '/products/cr_magnetics' => 'blue_sparks/pages#show', :slug => '/products/cr_magnetics'
  match '/products/cybectec' => 'blue_sparks/pages#show', :slug => '/products/cybectec'
  match '/products/fluke' => 'blue_sparks/pages#show', :slug => '/products/fluke'
  match '/products/infratec' => 'blue_sparks/pages#show', :slug => '/products/infratec'
  match '/products/nokian_capacitors' => 'blue_sparks/pages#show', :slug => '/products/nokian_capacitors'
  match '/products/qualitrol' => 'blue_sparks/pages#show', :slug => '/products/qualitrol'
  match '/products/vectek' => 'blue_sparks/pages#show', :slug => '/products/vectek'

  match '/services/engineering' => 'blue_sparks/pages#show', :slug => '/services/engineering'
  match '/services/training' => 'blue_sparks/pages#show', :slug => '/services/training'

  match '/company/your_trusted_partner' => 'blue_sparks/pages#show', :slug => '/company/your_trusted_partner'
  match '/company/contact_us' => 'blue_sparks/pages#show', :slug => '/company/contact_us'
  match '/company/our_clientele' => 'blue_sparks/pages#show', :slug => '/company/our_clientele'
  match '/company/careers_with_us' => 'blue_sparks/pages#show', :slug => '/company/careers_with_us'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/views/layouts/_footer.html.haml
.row.sitemap
  .span2#solutions
    .title SOLUTIONS
    %br
    = link_to "Electrical safety", solutions_electrical_safety_path
    = link_to "Power quality", solutions_power_quality_path
    = link_to "Energy management", solutions_energy_management_path
  .span2#products
    .title PRODUCTS
    %br
    = link_to "Algodue", products_algodue_path
    = link_to "Atlantic Scientific", products_atlantic_scientific_path
    = link_to "Bender", products_bender_path
    = link_to "CR Magnetics", products_cr_magnetics_path
    = link_to "Cybectec", products_cybectec_path
  .span2
    %br
    %br
    = link_to "Fluke", products_fluke_path
    = link_to "Infratec", products_infratec_path
    = link_to "Nokian Capacitors", products_nokian_capacitors_path
    = link_to "Qualitrol", products_qualitrol_path
    = link_to "Vectek", products_vectek_path
  .span2#services
    .title SERVICES
    %br
    = link_to "Engineering", services_engineering_path
    = link_to "Training", services_training_path
  .span2#company
    .title COMPANY
    %br
    = link_to "Your trusted partner",  company_your_trusted_partner_path
    = link_to "Our clientele",  company_our_clientele_path
    = link_to "Careers with us", company_careers_with_us_path
    = link_to "Contact us", company_contact_us_path
  .span2#contactus
    .title FEEL FREE TO CONTACT US
    %strong Phone:
    %br
    (+65) 6893-5796 or 
    %br
    (+65) 9818-9612
    %br
    %strong Enquiries:
    = mail_to "info@eetarp.com.sg"
    %br
    %strong Services:
    %br
    = mail_to "service@eetarp.com.sg"
.row.footer
  .span12
    Copyright ® 2007 Eetarp Engineering Pte Ltd. All rights reserved.
    %a.email.pull-right{:href => "http://www.eetarp.com.sg/cgi-bin/webmanager/webmail.cgi", :target => 'blank'}
      %i.icon-envelope.icon-white

app/views/layouts/_navbar.html.haml
%ul.navbar.clearfix
  %li#brand.pull-left
    %a{:href => "/"}
      = image_tag('logo.png')
  %li.pull-left
    = link_to "SOLUTIONS",  solutions_path, :id => "solutions"
  %li.pull-left
    = link_to "PRODUCTS",  products_path, :id => "products"
  %li.pull-left
    = link_to "SERVICES",  services_path, :id => "services"
  %li.pull-right
    = link_to "COMPANY",  company_path, :id => "company"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{ :rel => 'shortcut icon', :href => '/assets/eetarp.ico', :type => 'image/x-icon'}
    %title Eetarp Engineeering Group
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    :javascript
      $(document).ready(function(){
        $('.up-down.one').mouseover(function(){
          $('.default1').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default1').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.two').mouseover(function(){
          $('.default2').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default2').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.three').mouseover(function(){
          $('.default3').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default3').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.four').mouseover(function(){
          $('.default4').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default4').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.five').mouseover(function(){
          $('.default5').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default5').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.six').mouseover(function(){
          $('.default6').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default6').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.seven').mouseover(function(){
          $('.default7').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default7').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.eight').mouseover(function(){
          $('.default8').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default8').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.nine').mouseover(function(){
          $('.default9').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default9').stop().animate({
            height: 290 
          }, 200);   
        })

        $('.up-down.ten').mouseover(function(){
          $('.default10').stop().animate({
            height: 255    
          }, 200);                        
        }).mouseout(function(){
          $('.default10').stop().animate({
            height: 290 
          }, 200);   
        })
      })
  %body
    .container
      = render 'layouts/navbar'
      = yield
      = render 'layouts/footer'

app/views/pages/company.html.haml
.row.highlights#company
  %a.span3.up-down.one{ :href => "/company/your_trusted_partner" }
    .slide.default1
      .titlebox
      .title
        YOUR TRUSTED PARTNER
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.two{ :href => "/company/our_clientele" }
    .slide.default2
      .titlebox
      .title
        OUR CLIENTELE
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.three{ :href => "/company/careers_with_us" }
    .slide.default3
      .titlebox
      .title
        CAREERS WITH US
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.four{ :href => "/company/contact_us" }
    .slide.default4
      .titlebox
      .title
        CONTACT US
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
:javascript
  $("a#company").addClass("active");
  document.title = 'Eetarp Engineering Group | Company';

app/views/pages/company/careers.html.haml
.company
  .title
    CAREERS
  .content
    %p
      We ensure equal employment opportunities within an exciting and challenging working environment that allows each employee to reach their full potential.
    %Strong Current Vacancies:
    %ul
      %li Sales Engineers (for Singapore and Kuala Lumpur Office)
      %li Electrical Engineers (for Singapore and Kuala Lumpur Office)
    %Strong Qualification/Experience:
    %br
    %em for Sales Engineers
    %ul
      %li Diploma/Degree in Electrical or Electronics Engineering
      %li 1 – 2 years or more technical sales experience
    %em for Electrical Engineers
    %ul
      %li Diploma/Degree in Electrical or Electronics Engineering
      %li 1 – 2 years or more working experience in electrical engineering filed
    %p
      Please email your application together with recent photograph, resume and indicate your current and expected salaries to:
      = mail_to "hr@eetarp.com.sg"

app/views/pages/company/careers_with_us.html.haml
.company
  .content.clearfix
    %H1 CAREERS WITH US
    .image.pull-right
      = image_tag('career.jpg')
    %p
      We ensure equal employment opportunities within an exciting and challenging working environment that allows each employee to reach their full potential.
    %Strong Current Vacancies:
    %ul
      %li Sales Engineers (for Singapore and Kuala Lumpur Office)
      %li Electrical Engineers (for Singapore and Kuala Lumpur Office)
    %Strong Qualification/Experience:
    %br
    %em for Sales Engineers
    %ul
      %li Diploma/Degree in Electrical or Electronics Engineering
      %li 1 – 2 years or more technical sales experience
    %em for Electrical Engineers
    %ul
      %li Diploma/Degree in Electrical or Electronics Engineering
      %li 1 – 2 years or more working experience in electrical engineering filed
    %p
      Please email your application together with recent photograph, resume and indicate your current and expected salaries to:
      = mail_to "hr@eetarp.com.sg"
:javascript
  document.title = 'Eetarp Engineering Group | Careers with us';

app/views/pages/company/contact_us.html.haml
.company#contact_us
  .content
    %h1 CONTACT US
    .addresses.singapore.clearfix
      %address.pull-left
        %h4 Headquarter:
        %strong Eetarp Engineeering Pte Ltd
        ( 
        %a{:href => "http://maps.google.com/maps?saddr=&daddr=1.454246,103.796293", :target => 'blank'}
          get direction
        )
        %br
        21, Woodlands Industrial Park E1,
        %br
        = "#02-08, Singapore 757720"
        %br
        Phone: (+65) 6893-5796 or (+65) 9818-9612
        %br
        Fax: (+65) 6891-1857
        %br
        Enquiries: 
        = mail_to "info@eetarp.com.sg"
        %br
        Services: 
        = mail_to "service@eetarp.com.sg"
      .map.pull-right
        = image_tag('singaporemap.png')
    .addresses.malaysia.clearfix
      %address.pull-left
        %h4 Subsidiary:
        %strong Eetarp Engineering (M) Sdn Bhd
        ( 
        %a{:href => "http://maps.google.com/maps?saddr=&daddr=3.1129116,101.62218419999999", :target => 'blank'}
          get direction
        )
        %br
        Suite 1502, Lobby 1, Block A, Damansara Intan
        %br
        No. 1, Jalan SS20/27, 47400 Petaling Jaya, Selangor, Malaysia
        %br
        Phone: (+60) 3-7729-3973
        %br
        Fax: (+60) 3-7729-8973
        %br
        Email: 
        = mail_to "info@eetarp.com.sg"
      .map.pull-right
        = image_tag('malaysiamap.png')
:javascript
  document.title = 'Eetarp Engineering Group | Contact us';

app/views/pages/company/our_clientele.html.haml
.company
  .content.clearfix
    %H1 OUR CLIENTELE
    .image.pull-right
      = image_tag('clientele.jpg')
    %p
      Our products and services are used in a wide range of industries:
    %ul
      %li Hospitals
      %li Navy vessels and passenger cruise ships
      %li Oil and gas production platforms
      %li Petrochemical plants
      %li Oil refineries
      %li Power generation, transmission and distribution utilities
      %li Refuse incineration plants
      %li Mass rapid transit systems
      %li Mining industry
      %li Semiconductor plants
      %li Pharmaceutical and biochemical plants
      %li Military facilities
      %li Water treatment plants
      %li Telecommunications
      %li Data centers
      %li Facility management companies
      %li Switchboard manufacturers and system integrators
:javascript
  document.title = 'Eetarp Engineering Group | Our clientele';

app/views/pages/company/your_trusted_partner.html.haml
.company
  .content.clearfix
    %h1 YOUR TRUSTED PARTNER
    .image.pull-right
      = image_tag('trust.jpg')
    %p
      Our organization, 
      = succeed ',' do
        %strong Eetarp Engineering Group
      is a renowned Singapore-based multi-national engineering company. From our humble beginnings in 1999, we have gained our clients' confidence by providing them with the latest technology and reliable solutions in the fields of 
      = succeed ', ' do
        %strong electrical safety
      = succeed ', ' do
        %strong power quality
      and 
      %strong
        energy management
      for their mission-critical and high-value investments.
    %p  
      We are committed in adding value to the supply chain between our clients
      and principals.
    %p
      Through long-term partnership with our principals, onsite experience, continuous training of our engineers, and investment in advanced tools and equipment, our clients can be assured that we understand their needs better. Our clients trust that the solutions we select are the most reliable, optimal, easy to operate and competitive. Site testing, commissioning time and maintenance cost will be reduced significantly as the solutions are designed based on the proven products available from our principals.
    %p
      %strong
        Our solutions
      are to help our clients maintain the highest level of electrical safety, reliable power supply quality and reduce energy consumption.
    %p
      We provide a whole range of products ranging from discrete devices to integrated solutions and from portable to permanently installed web-based monitoring and reporting, complete with data storage and database management systems to meet every unique requirement of our clients.
    %p
      %strong
        Our clients
      span the whole spectrum of industries from land-based data
      centers, hospitals, semiconductor manufacturing plants, power generation
      and electrical substations, commercial buildings, electrical vehicles, solar installations to offshore oil rigs, FPSO, cruise ships and naval ships.
    %p
      In return for our clients’ continued support, we share with them our knowledge and expertise by conducting regular classroom and onsite trainings as well as technical seminars.
    %p
      %strong
        Our vision
      of being a customer-focused, technology-driven and service-
      oriented company has given us the impetus to continuously improve and innovate.
:javascript
  document.title = 'Eetarp Engineering Group | Your trusted partner';

app/views/pages/home.html.haml
#wrapper
  .slider-wrapper.theme-default
    .ribbon
    #slider.nivoSlider
      = image_tag("electricalsafety.jpg", :title => "#caption1")
      = image_tag("powerquality.jpg", :title => "#caption2")
      = image_tag("energymanagement.jpg", :title => "#caption3")
    #caption1.nivo-html-caption
      %strong ELECTRICAL SAFETY
      %span
      = succeed "." do
        %em In almost all aspects of our daily life, safety is indispensable
    #caption2.nivo-html-caption
      %strong POWER QUALITY
      %span
      = succeed "." do
        %em Reliable and continuous power supply for our daily activities
    #caption3.nivo-html-caption
      %strong ENERGY MANAGEMENT
      %span
      = succeed "." do
        %em Energy consumption is one of the most significant costs in a company
.row.highlights#home
  %a.span3.up-down.one{ :href => "/company/your_trusted_partner" }
    .slide.default1
      .titlebox
      .title
        YOUR TRUSTED PARTNER
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.two{ :href => "/solutions" }
    .slide.default2
      .titlebox
      .title
        YOUR RIGHT SOLUTIONS
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.three{ :href => "/products" }
    .slide.default3
      .titlebox
      .title
        BROWSE OUR PRODUCTS
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.four{ :href => "/services" }
    .slide.default4
      .titlebox
      .title
        ENGAGE OUR SERVICES
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white

app/views/pages/products.html.haml
.row.highlights#products
  %a.span3.up-down.one{ :href => "/products/algodue" }
    .slide.default1
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.two{ :href => "/products/atlantic_scientific" }
    .slide.default2
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.three{ :href => "/products/bender" }
    .slide.default3
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.four{ :href => "/products/cr_magnetics" }
    .slide.default4
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
.row.highlights#products
  %a.span3.up-down.five{ :href => "/products/cybectec" }
    .slide.default5
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.six{ :href => "/products/fluke" }
    .slide.default6
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.seven{ :href => "/products/infratec" }
    .slide.default7
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.eight{ :href => "/products/nokian_capacitors" }
    .slide.default8
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
.row.highlights#products
  %a.span3.up-down.nine{ :href => "/products/qualitrol" }
    .slide.default9
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
  %a.span3.up-down.ten{ :href => "/products/vectek" }
    .slide.default10
    .slide.onhover
      .link
        read more
        %i.icon-arrow-right.icon-white
:javascript
  $("a#products").addClass("active");
  document.title = 'Eetarp Engineering Group | Products';

app/views/pages/products/algodue.html.haml
.products
  .content.clearfix
    %h1 ALGODUE
    .image.pull-right
      = image_tag('algodue.jpg')
    %h3 Algodue Elettronica srl, Italy
    %p
      Algodue Elettronica have been active on the international market for several years they have acquired a wide experience both in customer care and solution providing.
    %p
      They steadily invest in new technology as well as in new solutions to enhance and increase the product range and to guarantee a service, both to keep up with the times.
    %p
      Thanks to the interplay of the wide range of products, their flexibility and the 20-years experience in the energy sector help us offer application-oriented solutions and achieve customer satisfaction.
    %ul
      %li High performance power quality meters with RS485 communication (Modbus, Profibus-DP, LON), TCP/IP, analogue and pulse outputs
      %li Accuracy according to EN62053
      %li Large graphic display for waveform capture, harmonics analysis, logging and Sags & Swells detection
      %li For billing, energy meter according to EN50470 with direct measurement or through 1/5A CT
:javascript
  document.title = 'Eetarp Engineering Group | Algodue';

app/views/pages/products/atlantic_scientific.html.haml
.products
  .content.clearfix
    %h1 ATLANTIC SCIENTIFIC
    .image.pull-right
      = image_tag('asc.jpg')
    %h3 Atlantic Scientific Corporation, USA
    %p
      Atlantic Scientific Corporation was founded in 1977 and are the surge protection division of the MTL Instruments Group.
    %p
      Atlantic Scientific has extensive experience in the design and manufacture of surge protection devices for a wide range of applications. Their innovative patented technology has provided industry firsts in many areas. They developed the first five stage hybrid technology, the first modular snap-in and plug-in data protection, the first UL Certified Cat 5 compliant surge protectors, and the first customer configurable power protection platform designed with slide-in "mix and match" data protection modules for complete upgradable protection of all sensitive electronic equipment.
    %ul
      %li AC and DC surge protection for total facility protection with maximum surge capacity of up to 300kA per phase
      %li Surge protection devices for data, network, NTU, fire alarm, security, PLC, cable TV, digital satellite, video, etc
:javascript
  document.title = 'Eetarp Engineering Group | Atlantic Scientific';

app/views/pages/products/bender.html.haml
.products
  .content.clearfix
    %h1 BENDER
    .image.pull-right
      = image_tag('bender.jpg')
    %h3 Dipl-Ing W Bender GmbH & Co KG, Germany
    %p
      For more than 60 years BENDER's objective has been to provide solutions for safe and secure power supplies, especially where high levels of safety are important. Using the latest technology, BENDER offers measuring, monitoring and protective systems to monitor the electrical safety of machines and systems in order to provide an early warning before critical operating conditions result in damage to property and interruptions to operations involving considerable costs or before the life and health of people is endangered. Complete testing systems to test the electrical safety of devices and systems, including data management software, supplement the product range. 
    %p
      The products cover a wide range of applications extending from building services engineering, hospitals through all types of industrial applications and power supply and distribution to traffic engineering.
    %ul
      %li A-ISOMETER insulation monitoring with earth-fault detection system (EDS)
      %li Isolated power system for hospital application
      %li Residual current monitoring for critical load
      %li Branch circuit current monitoring system for final circuit
      %li Touch control panel for operating theatre room
      %li Voltage, current, asymmetry, phase sequence and frequency relays
      %li Electrical safety tester for medical equipment according to IEC60601/IEC62353
      %li Electrical safety monitoring for photovoltaic system
:javascript
  document.title = 'Eetarp Engineering Group | Bender';

app/views/pages/products/cr_magnetics.html.haml
.products
  .content.clearfix
    %h1 CR MAGNETICS
    .image.pull-right
      = image_tag('crmagnetics.jpg')
    %h3 CR Magnetics, USA
    %p
      CR Magnetics is an American Company specialised in the manufacturing and distributing of current sensing problems devices.
    %ul
      %li AC and DC voltage transducers
      %li AC and DC current transducers
      %li Split core transducers
      %li AC/DC current switches
      %li AC/DC current or phase loss relays
      %li Display and indicators
:javascript
  document.title = 'Eetarp Engineering Group | CR Magnetics';

app/views/pages/products/cybectec.html.haml
.products
  .content.clearfix
    %h1 CYBECTEC
    .image.pull-right
      = image_tag('cybectec.jpg')
    %h3 Cybectec Inc, Canada
    %p
      CYBECTEC is now part of Cooper Power System’s Energy Automation Solutions group. The Energy Automation Solutions group was created to provide comprehensive automation solutions that integrate both legacy and new transmission and distribution products.
    %p
      Cybectec was founded in 1980 to provide technical consulting services and to develop custom hardware and software systems. Since the beginning, Cybectec has provided its customers with solutions that meet the most demanding real-time and reliability requirements in a number of areas, including electrical power substation automation, integration, communication and instrumentation.
    %p
      Working with its clients in the power industry, Cybectec has developed families of products specially designed to assist utilities in modernizing their automation systems and integrating new intelligent electronic devices, with maximum return on investment.
    %p
      Cybectec solutions are already implemented in some of the largest utilities in North America. It has longstanding expertise in custom and consulting services, and an outstanding reputation for customer support, making it a leading player in the field of enterprise automation solutions for the power industry.
    %ul
      %li Substation modernization platform for the substation integration and automation
      %li Provides data encryption to meet NERC CIP requirements
      %li Provides complete control and a secure access point to IEDs via pass-through function
      %li Smart grid solutions via IEC61850 communication
      %li IEC60870-101/104 to OPC server protocol translator
      %li Customized Human Machine Interface (HMI), such as the visual T&D software for data acquisition and analysis
:javascript
  document.title = 'Eetarp Engineering Group | Cybectec';

app/views/pages/products/fluke.html.haml
.products
  .content.clearfix
    %h1 FLUKE
    .image.pull-right
      = image_tag('fluke.jpg')
    %h3 Fluke Corp, USA
    %p
      Since its founding in 1948, FLUKE has helped define and grow a unique technology market, providing testing and troubleshooting capabilities that have grown to mission critical status in manufacturing and service industries. Every new manufacturing plant, office or facility built today represents another potential customer for Fluke products.
    %p
      From industrial electronic installation, maintenance and service, to precision measurement and quality control, Fluke tools help keep business and industry around the globe up and running. Typical customers and users include technicians, engineers, metrologists, and computer network professionals -- people who stake their reputation on their tools, and use tools to help extend their personal power and abilities.
    %p
      Fluke has achieved the number one or number two position in every market in which it competes. The Fluke brand has a reputation for portability, ruggedness, safety, ease of use and rigid standards of quality.
    %ul
      %li Power quality recorder fully comply with IEC61000-4-30 Class A
      %li Power quality analyzer with threshold trigger recording and transient recording features
      %li Power logger with compact and rugged design with more than 1 month recording
      %li High precision power analyzers
      %li Insulation and earth testers with stakeless testing
      %li Portable measuring tools like current clamp meter
:javascript
  document.title = 'Eetarp Engineering Group | Fluke';

app/views/pages/products/infratec.html.haml
.products
  .content.clearfix
    %h1 INFRATEC
    .image.pull-right
      = image_tag('infratec.jpg')
    %h3 InfraTec GmbH, Germany
    %p
      InfraTec was founded in 1991. Through many years' development and international experience, InfraTec can offer any advice for the configuration of your thermographic system, also provide you with thermographic solutions tailored to your special application, design solutions for industrial automation using thermographic systems, start with a detailed problem analysis up to the delivery of the turn-key solution and its maintenance.
    %p
      The excellent thermal and geometrical resolution, rugged user-friendly design, state-of-the-art digital technology, powerful image analysis, comprehensive equipment, good price/performance ratio and low operating costs are substantial advantages of the thermographic solutions offered by InfraTec.
    %ul
      %li Active thermography for non-destructive material testing
      %li Turnkey thermography automatic system for early fire detection in refuse incineration bunkers and quality control in automatic production process
      %li High-end thermography camera for industrial and medical research and development
      %li Predictive maintenance and building inspection
:javascript
  document.title = 'Eetarp Engineering Group | Infratec';

app/views/pages/products/nokian_capacitors.html.haml
.products
  .content.clearfix
    %h1 NOKIAN CAPACITORS
    .image.pull-right
      = image_tag('nokiancap.jpg')
    %h3 Nokian Capacitors, Finland
    %p
      Nokian Capacitors Ltd. engineers and manufactures equipment and systems for reactive power compensation and harmonic filtering. The customers include housing and commercial premises, construction firms and industrial enterprises as well as companies engaged in the production, transmission and distribution of energy worldwide.
    %p
      The scope of Nokian Capacitors' 'products ranges from low and high voltage capacitoers and electronic equipment to air core reactors and compensation system.Products are used to reduce overall power consumption, to avoid the need for oversized power systems and to eliminate disturbances.
    %p
      With their products and expertise, customers see immediate cost savings and rapid repayment of the investment ,environmental benefits through saving energy and more efficient power system as well.
    %ul
      %li HV, MV, LV capacitor banks to improve transmission capacity and improve power factor
      %li Active and passive harmonics filters for harmonic filtering and power factor correction to improve power quality
      %li Air core reactor for current limiting, neutral earthing, shunt and other application
      %li Design according to IEC60871 (high voltage)/IEC60831 (low voltage)
:javascript
  document.title = 'Eetarp Engineering Group | Nokian Capacitors';

app/views/pages/products/qualitrol.html.haml
.products
  .content.clearfix
    %h1 QUALITROL
    .image.pull-right
      = image_tag('qualitrol.jpg')
    %h3 Qualitrol Corp, USA
    %ul
      %li Digital fault recorder (BEN6000 and IDM)
      %li Travelling wave fault locator
      %li Fault investigation and location software
      %li Performance measuring and monitoring device – QWave PMD-A fully compliant with IEC61000-4-30 Class A PQ monitoring
:javascript
  document.title = 'Eetarp Engineering Group | Qualitrol';